# This file contains codes for testing the Gradient-Descent based solvers to find input latent code given an output shape.

## TO-DO : The code will be consisting of the following  experiments:
"""
Setup: Extract a random latent code from any input file (z1). Also have a shape-code pair (z2,S2).
Model: IMNET Decoder.
The Gradient descent solvers I am going to use are Adam and SGD from PyTorch.

Experiment 1: Use a random latent code generated by a PRNG.
Experiment 2: Use the code z1 that lies in the distribution.
Experiment 3: Use z2+noise as initialization.
            - a) Gaussian Noise
            - b) Salt and Pepper Noise
            - c) Uniform Noise

""" 

